---
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.rbac.labels }}
  labels:
    {{- toYaml .Values.rbac.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.rbac.annotations }}
  annotations:
    {{- toYaml .Values.rbac.annotations | nindent 4 }}
  {{- end }}
  name:  {{ .Release.Name }}-service-account
