
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  {{- if .Values.rbac.labels }}
  labels:
    {{- toYaml .Values.rbac.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.rbac.annotations }}
  annotations:
    {{- toYaml .Values.rbac.annotations | nindent 4 }}
  {{- end }}
  name: {{ .Release.Name }}-cluster-role
rules:
  - apiGroups:
      - ""
      - extensions
      - apps
      - networking.k8s.io
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - ingresses
    verbs:
      - list
      - get
      - watch
