---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  {{- if .Values.rbac.labels }}
  labels:
    {{- toYaml .Values.rbac.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.rbac.annotations }}
  annotations:
    {{- toYaml .Values.rbac.annotations | nindent 4 }}
  {{- end }}
  name: {{ .Release.Name }}-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-service-account
    namespace: {{ .Release.Namespace }}
