apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubeshark-hub
    {{- if .Values.hub.labels }}
    {{- toYaml .Values.hub.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.hub.annotations }}
  annotations:
    {{- toYaml .Values.hub.annotations | nindent 4 }}
  {{- end }}
  name: {{ .Release.Name }}-hub  # Update the Deployment name to include the release name
spec:
  replicas: {{ .Values.hub.replicas }}   # Use the replicas variable from the values file
  selector:
    matchLabels:
      app: {{ .Release.Name }}-hub
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-hub
        {{- if .Values.hub.labels }}
          {{ toYaml .Values.hub.labels | nindent 8 }}
        {{- end }}
      {{- if .Values.hub.annotations }}
      annotations:
        {{ toYaml .Values.hub.annotations | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - command:
            - ./hub
            {{ .Values.hub.debug | ternary "- -debug" "" }}
          env:
            - name: POD_REGEX
              value: '{{ .Values.tap.regex }}'
            - name: NAMESPACES
              value: '{{ gt (len .Values.tap.config.namespaces) 0 | ternary (join "," .Values.tap.namespaces) "" }}'
            - name: LICENSE
              value: '{{ .Values.license }}'
            - name: SCRIPTING_ENV
              value: '{{ .Values.scripting.env | toJson }}'
            - name: SCRIPTING_SCRIPTS
              value: '[]'
            - name: AUTH_APPROVED_DOMAINS
              value: '{{ gt (len .Values.ingress.auth.approveddomains) 0 | ternary (join "," .Values.ingress.auth.approveddomains) "" }}'
          image: '{{ .Values.hub.image.registry }}/{{ .Values.hub.image.name }}:{{ .Values.hub.image.tag }}'
          imagePullPolicy: {{ .Values.hub.imagepullpolicy }}
          name: kubeshark-hub
          ports:
            - containerPort: 80   # Expose port 80 in the container
              name: http-api
          {{- if .Values.hub.resources }}
          resources:
            {{ toYaml .Values.hub.resources | nindent 12 }}
          {{- end }}
      {{- if .Values.hub.tolerations }}
      tolerations:
        {{ toYaml .Values.hub.tolerations | nindent 8 }}
      {{- end }}
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: {{ .Release.Name }}-service-account
      terminationGracePeriodSeconds: 0
