apiVersion: v1
kind: Service
metadata:
  {{- if .Values.hub.service.labels }}
  labels:
    {{ toYaml .Values.hub.service.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.hub.service.annotations }}
  annotations:
    {{ toYaml .Values.hub.service.annotations | nindent 4 }}
  {{- end }}
  name: {{ .Release.Name }}-hub
spec:
  ports:
    - name: http-api
      port: {{ .Values.hub.service.port }}
      targetPort: http-api
  selector:
    app: {{ .Release.Name }}-hub
  type: {{ .Values.hub.service.type }} 
