apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app:  {{ .Release.Name }}-front
  {{- if .Values.front.labels }}
    {{- toYaml .Values.front.labels | nindent 4 }}
  {{- end }}
  annotations:
  {{- if .Values.front.annotations }}
    {{- toYaml .Values.front.annotations | nindent 4 }}
  {{- end }}
  name: {{ .Release.Name }}-front  # Update the Deployment name to include the release name
spec:
  replicas: {{ .Values.front.replicas }}   # Use the replicas variable from the values file
  selector:
    matchLabels:
      app:  {{ .Release.Name }}-front
  template:
    metadata:
      labels:
        app:  {{ .Release.Name }}-front
        {{- if .Values.front.labels }}
{{ toYaml .Values.front.labels | nindent 8 }}
{{- end }}
      annotations:
        {{- if .Values.front.annotations }}
{{ toYaml .Values.front.annotations | nindent 8 }}
{{- end }}
    spec:
      containers:
        - env:
            - name: REACT_APP_DEFAULT_FILTER
              value: ' '
            - name: REACT_APP_HUB_HOST
              value: ' '
            - name: REACT_APP_HUB_PORT
              value: '{{ .Values.hub.service.port }}'   # Use the hubPort variable from the values file
          image: '{{ .Values.front.image.registry }}/{{ .Values.front.image.name }}:{{ .Values.front.image.tag }}'  # Use the image variables from the values file
          imagePullPolicy: {{ .Values.front.imagePullPolicy }}  # Use the imagePullPolicy variable from the values file
          name: kubeshark-front
          ports:
            - containerPort: 80
              name: http-frontend  # Expose port 80 in the container
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: 80
            timeoutSeconds: 1
{{- if .Values.front.resources }}
          resources:
{{ toYaml .Values.front.resources | nindent 12 }}   # Use the resources variable from the values file
{{- end }}
{{- if .Values.front.tolerations }}
      tolerations:
{{ toYaml .Values.front.tolerations | nindent 8 }}   # Use the tolerations variable from the values file
{{- end }}
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName:  {{ .Release.Name }}-service-account
      terminationGracePeriodSeconds: 0
