---
{{- if .Values.tap.persistentstorage }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- if .Values.tap.labels }}
  labels:
    {{- toYaml .Values.tap.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.tap.annotations }}
  annotations:
    {{- toYaml .Values.tap.annotations | nindent 4 }}
  {{- end }}
  name: {{ .Release.Name }}-persistent-worker-tap
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.tap.storagelimit }}
  storageClassName: {{ .Values.tap.storageclass }}
{{- end }}
