---
{{- if .Values.ingressClass.enabled }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  {{- if .Values.ingressClass.labels }}
  labels:
    {{- toYaml .Values.ingressClass.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.ingressClass.annotations }}
  annotations:
    {{- toYaml .Values.ingressClass.annotations | nindent 4 }}
  {{- end }}
  name: {{ .Release.Name }}-ingress-class
spec:
  controller: {{ .Values.ingressClass.controller }}
{{- end }}
