---
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: {{ .Values.ingress.certmanager }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
  {{- end }}
  labels:
  {{- if .Values.ingress.labels }}
    {{- toYaml .Values.ingress.labels | nindent 4 }}
  {{- end }}
  name: {{ .Release.Name }}-ingress
spec:
  {{- if .Values.ingressClass.enabled }}
  ingressClassName: {{ .Release.Name }}-ingress-class  # Use the custom ingress class name
  {{- else }}
  ingressClassName: {{ .Values.ingress.classname }}  # Use the specified value for ingress class name
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-hub
                port:
                  number: 80
            path: /api(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: {{ .Release.Name }}-front
                port:
                  number: 80
            path: /()(.*)
            pathType: Prefix
  tls:
  {{- if gt (len .Values.ingress.tls) 0}}
    {{- toYaml .Values.ingress.tls | nindent 2 }}
  {{- end }}
{{- end }}
